# Tensors

Just a general note, if we want to avoid a copy when passing to `torch.tensor()` constructor, we use `requires_grad()` or in case of converting Numpy array to tensor use, `torch.as_tensor()`

In [1]:
import torch

In [2]:
sc = torch.tensor(7)
sc

tensor(7)

In [4]:
sc.ndim

0

In [5]:
sc.item() # Get value from 0 dim tensor

7

In [6]:
vec = torch.tensor([7,7]) # Torch vector tensor
vec

tensor([7, 7])

In [10]:
vec[1].item() # Only applies to scalars
vec.ndim

1

In [11]:
vec.shape

torch.Size([2])

In [12]:
sc.shape

torch.Size([])

In [13]:
mat = torch.tensor([[7,1],[12,5]])
print(mat.ndim, mat.shape) # 2, (2,2)

2 torch.Size([2, 2])


In [18]:
# Create a tensor or shape 3,1,6
anotherTensor = torch.tensor([[[1,2,3,4,5,6]],[[7,8,9,10,11,12]],[[13,14,15,16,17,18]]])

In [19]:
print(f"{anotherTensor.shape}\n{anotherTensor.ndim}")

torch.Size([3, 1, 6])
3


# Random Num Generation

In [41]:
randomTensor = torch.rand(size=(3,4))
randomTensor

tensor([[0.8849, 0.4706, 0.4518, 0.9077],
        [0.6548, 0.2338, 0.5496, 0.2616],
        [0.2566, 0.8070, 0.9594, 0.7233]])

In [42]:
randomTensor = torch.rand(size=(3,224,224))

In [43]:
randomTensor

tensor([[[0.1351, 0.5473, 0.1963,  ..., 0.6474, 0.2476, 0.5619],
         [0.9179, 0.0119, 0.4874,  ..., 0.5411, 0.4647, 0.4445],
         [0.3669, 0.7795, 0.4101,  ..., 0.6172, 0.2202, 0.2165],
         ...,
         [0.8329, 0.9001, 0.5604,  ..., 0.1775, 0.4302, 0.8758],
         [0.4417, 0.8881, 0.5891,  ..., 0.6169, 0.5214, 0.2454],
         [0.7678, 0.8824, 0.9224,  ..., 0.3555, 0.4436, 0.2639]],

        [[0.1289, 0.1739, 0.3182,  ..., 0.4495, 0.2765, 0.9773],
         [0.2458, 0.8705, 0.4317,  ..., 0.5178, 0.7626, 0.7995],
         [0.6960, 0.3499, 0.4538,  ..., 0.8106, 0.2110, 0.0726],
         ...,
         [0.2185, 0.9797, 0.7376,  ..., 0.3738, 0.5224, 0.6360],
         [0.2404, 0.4371, 0.5105,  ..., 0.1679, 0.1285, 0.0475],
         [0.1097, 0.8159, 0.7454,  ..., 0.4849, 0.6473, 0.5383]],

        [[0.7862, 0.1403, 0.1553,  ..., 0.3926, 0.2837, 0.3227],
         [0.2410, 0.8865, 0.1038,  ..., 0.5308, 0.8343, 0.3004],
         [0.0940, 0.1651, 0.3386,  ..., 0.2803, 0.4384, 0.

In [44]:
zeroedTensor = torch.zeros(size=(3,224,224))

In [48]:
arrayLike = torch.arange(0,10)
arrayLike

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
same = torch.zeros_like(randomTensor)

In [50]:
same

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [55]:
float32Tensor = torch.tensor([3.0, 4.0, 69.0], dtype=None, requires_grad=True)# Default dtype is float32

In [54]:
float32Tensor

tensor([ 3.,  4., 69.])

$\textbf{Important note: }$ 

`requires_grad` $\text{is a parameter that allows the autograd engine to later compute the gradients of the tensor with repect to a loss function menitoned in the program}$

This keeps track of all the operations in the tensor from that point onward

This enables us to just define the forward computation and PyTorch handles the gradients automatically. We don't have to write the backpropagation algoritm manually. We just call `y.backward()` where `y` is the tensor

## Tensors are Immutable

In [56]:
torch.mul(float32Tensor, 10)

tensor([ 30.,  40., 690.], grad_fn=<MulBackward0>)

In [59]:
(float32Tensor * float32Tensor)[0].item() # Element wise mulitplication

9.0

In [62]:
(torch.matmul(float32Tensor, float32Tensor)).item()

4786.0

In [65]:
# Visualization test
x = torch.randn(3,4)
y = torch.randn(4)
torch.matmul(x,y)

tensor([ 1.8254,  1.1515, -0.4472])

In [71]:
someObject = torch.tensor([[[5,9],[12,16]],[[99,100],[0,0]]])
someObject.shape, someObject.ndim

(torch.Size([2, 2, 2]), 3)

In [72]:
someObject.max(), someObject.min(), someObject.argmax(), someObject.argmin()

(tensor(100), tensor(0), tensor(5), tensor(6))

In [77]:
torch.mean(someObject.type(torch.float32)), torch.max(someObject), torch.min(someObject), torch.sum(someObject)

(tensor(30.1250), tensor(100), tensor(0), tensor(241))

In [79]:
someObject.reshape(8)

tensor([  5,   9,  12,  16,  99, 100,   0,   0])

When we use `torch.view()`, we just reshape the tensor. This effectively creates a new tensor. But the new tensor is referencing the same data as the original tensor(not a copy), so modifying the view tensor will also change the original tensor

In [80]:
z = someObject.view(2,2,2)

In [81]:
z

tensor([[[  5,   9],
         [ 12,  16]],

        [[ 99, 100],
         [  0,   0]]])

In [89]:
torch.stack([z,z], dim=0)

tensor([[[[  5,   9],
          [ 12,  16]],

         [[ 99, 100],
          [  0,   0]]],


        [[[  5,   9],
          [ 12,  16]],

         [[ 99, 100],
          [  0,   0]]]])

In [87]:
torch.squeeze(z)

tensor([[[  5,   9],
         [ 12,  16]],

        [[ 99, 100],
         [  0,   0]]])

There are two ways to index tensors

In [91]:
print(z[1])
print(z[1][0])
print(z[0][0][1])

tensor([[ 99, 100],
        [  0,   0]])
tensor([ 99, 100])
tensor(9)


In [99]:
print(z[:, :, :-1]) # Get all values of 1st and second dim, but exclude the last values in the 3rd dimension

print(z[:, :, -1:]) # Get all the values of 1st and 2nd dim, but only get the last value in the 3rd dimensio

tensor([[[ 5],
         [12]],

        [[99],
         [ 0]]])
tensor([[[  9],
         [ 16]],

        [[100],
         [  0]]])
