In [17]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [2]:
iris = load_iris()
X = iris.data
y = iris.target

In [16]:
def k_fold_split(X, y, k):
    n_samples = len(X)
    indices = np.arange(n_samples)
    np.random.shuffle(indices)
    #print(indices)

    fold_sizes = (n_samples // k) * np.ones(k, dtype=int)
    #print(fold_sizes)
    fold_sizes[:n_samples % k] += 1

    current = 0
    folds = []
    for fold_size in fold_sizes:
        start, stop = current , current + fold_size
        folds.append(indices[start:stop])
        current = stop
    return folds

k_fold_split(X,y, 10)

[array([130,  49,  43,  63, 118, 138,  96, 107, 119, 116, 120,  33, 129,
         45, 139]),
 array([ 18,  54,  12,   7,  88, 128, 126,  21, 140, 100,  65,  56,  57,
          2,  25]),
 array([109,  82,  62,  24,  11,   3,  36, 105, 144,  38,  35,  53, 148,
         93,  76]),
 array([113, 149,  41,  17,  68, 112,  16, 110,   1,  39,  52,  60, 104,
        123, 131]),
 array([ 75,  26, 102,  69,  42,  72,  73,  19,  46,  10, 141,  14, 136,
        111, 147]),
 array([ 22,  48,  77,  78, 135,  91,   8,  30, 143,   6,  31,  37,  66,
         87,  50]),
 array([ 23, 114,  40, 137,   5,  59,  80,  61,  13,  34, 127,  94, 145,
         99,  98]),
 array([  4,  15,  92,  58,   0,  67, 115, 108,  89,  95,  79,   9, 125,
         44,  97]),
 array([ 47,  71,  27, 122, 103, 146,  28,  90, 121,  55,  51,  32,  74,
         83, 106]),
 array([117, 132, 134, 133,  20,  84,  86, 124,  85,  70,  29, 142,  64,
         81, 101])]

In [26]:
def manualKFold(X, y, k = 10):
    folds = k_fold_split(X, y, k)

    scores = []

    for i in range(k):
        test_idx = folds[i]
        train_idx = np.hstack([folds[j] for j in range(k) if j!= i])

        model = LogisticRegression(max_iter=1000)
        X_train, y_train = X[train_idx], y[train_idx]
        X_test, y_test = X[test_idx], y[test_idx]

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        acc = accuracy_score(y_test, y_pred)

        scores.append(acc)

        print(f"Fold{i + 1}, Accuracy: {acc:.4f}")

        print(f"\nAverage Accuracy over {k} folds: {np.mean(scores):.4f}")

In [27]:
manualKFold(X, y, k = 10)

Fold1, Accuracy: 1.0000

Average Accuracy over 10 folds: 1.0000
Fold2, Accuracy: 0.9333

Average Accuracy over 10 folds: 0.9667
Fold3, Accuracy: 0.8000

Average Accuracy over 10 folds: 0.9111
Fold4, Accuracy: 0.9333

Average Accuracy over 10 folds: 0.9167
Fold5, Accuracy: 1.0000

Average Accuracy over 10 folds: 0.9333
Fold6, Accuracy: 1.0000

Average Accuracy over 10 folds: 0.9444
Fold7, Accuracy: 0.9333

Average Accuracy over 10 folds: 0.9429
Fold8, Accuracy: 0.9333

Average Accuracy over 10 folds: 0.9417
Fold9, Accuracy: 1.0000

Average Accuracy over 10 folds: 0.9481
Fold10, Accuracy: 1.0000

Average Accuracy over 10 folds: 0.9533
