# K-Nearest Neighbours

K-NN does not learn the model in the ways that we have studied statistical learning methods previously. It memorizes the dataset and only makes predictions when queried. This feature of K-NN is called lazy learning. 

Mostly useful in cases where dataset is small and relatively unfamiliar dataset.

The core idea is to compute distance between data points. If the feature space is continuous and equally scaled, use Euclidian distance. If the feature space is highly sparse, use Manhattan distance.

The main point being, K(number of neighbours) is the only hyperparameter in this learning. For high value of K, the variance is high and bias is low. And its opposite the other way.

To the K nearest neighbours, if uniform weighting is used, $w_i$ = 1. For other weighting schemes, the weights are given as some mathamatically sound formula.

The most common weighting scheme is inverse distance weighting. The closer the instance, the higher the weight.

In [6]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [7]:
iris = load_iris()
X = iris.data
y = iris.target

In [8]:
y_binary = np.where(y == 0, 1, 0)

X_train, X_test, y_train, y_test = train_test_split(X, y_binary, random_state=69, test_size=0.3)

In [9]:
print(X_train.shape)
print(X_test.shape)

(105, 4)
(45, 4)


In [10]:
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

In [16]:
def knn_predict(X_train, y_train, X_test, k=3):
    predictions = []
    for test_point in X_test:

        distances = [euclidean_distance(test_point, train_point) for train_point in X_train]
        #print(distances)
        
        k_indices = np.argsort(distances)[:k]
        print(k_indices)
        
        k_nearest_labels = y_train[k_indices]
        
        # Majority Voting, Most common labels
        most_common = np.bincount(k_nearest_labels).argmax()
        predictions.append(most_common)
    
    return np.array(predictions)

In [17]:
def accuracy(y_true, y_pred):
    return np.sum(y_true == y_pred) / len(y_true)

k = 3
y_pred = knn_predict(X_train, y_train, X_test, k)

acc = accuracy(y_test, y_pred)
print(f"Accuracy: {acc * 100:.2f}%")

[18 51 40]
[ 93 104  23]
[45 12 87]
[86  1 56]
[12 45 87]
[65 78 22]
[ 13  97 102]
[ 8 43 31]
[  8 103  43]
[47 67 65]
[ 2 61 36]
[ 30 103  33]
[98 91 25]
[11 75 14]
[ 5 85 63]
[60 69 58]
[90 74  3]
[10 55 95]
[97 96 13]
[ 1 56 86]
[35 95 31]
[39 29 13]
[99 27 21]
[67 45 47]
[103   8  31]
[12 67 45]
[46 35 95]
[31 35 95]
[37 92 90]
[51 40 87]
[91 88 24]
[98 91 88]
[77 47 67]
[84 28 75]
[ 30  33 103]
[95 31 35]
[98 88 91]
[32 97 58]
[79 23 73]
[84  1 56]
[78 22 65]
[46 15 85]
[32 97 96]
[52 99 91]
[79  7 73]
Accuracy: 100.00%
